orbs:
  release-workflows: 'hutson/library-release-workflows@4.3.3'
version: 2.1
workflows:
  build_test_deploy:
    jobs:
      - node_10_test_plan
      - release-workflows/lerna-deliver:
          context: github-interaction
          email: circleci@circleci
          filters:
            branches:
              only: prerelease/beta
          fingerprint: '48:0a:68:49:13:e2:09:20:66:3f:55:dd:0a:1a:ab:2a'
          fullname: CircleCI
          requires:
            - node_10_test_plan
      - release-workflows/lerna-deploy:
          context: npm-interaction
          filters:
            branches:
              only: prerelease/beta
          requires:
            - release-workflows/lerna-deliver
  version: 2
