version: 2.1
jobs:
  deliver:
    description: >
      Job for generating a release, along with corresponding git tags, for a
      Lerna-based mono-repository.
      https://circleci.com/orbs/registry/orb/hutson/library-release-workflows
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 58:7a:36:83:61:28:2c:c9:83:b1:c5:57:26:a9:fc:11
      - run: >-
          git config --global user.email "circleci@circleci" && git config --global user.name "CircleCI"
      - run: sudo apt install rsync
      - run: yarn install
      - run: yarn build
      - run: yarn test & yarn lint --quiet
      - run: yarn version:release --yes
  deploy:
    description: >
      Job for publishing multiple npm packages from a Lerna-based mono-repository to
      an npm-compatible package registry.
      https://circleci.com/orbs/registry/orb/hutson/library-release-workflows
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - run: yarn install
      - run: yarn global add @hutson/set-npm-auth-token-for-ci
      - run: set-npm-auth-token-for-ci
      - run: yarn publish:beta
workflows:
  version: 2
  build:
    jobs:
      - deliver:
          filters:
            branches:
              only: prerelease/beta
      - deploy:
          requires:
            - deliver
          filters:
            branches:
              only: prerelease/beta
