version: 2.1
jobs:
  git_hygiene:
    description: >
      Job for enforcing git hygiene such as commit-lint
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - run: yarn install
      - run: yarn commitlint-circle

  build_and_test:
    description: >
      Job for verifying build and test
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - run: sudo apt install rsync
      - run: yarn install
      - run: yarn build
      - run: yarn test & yarn lint

  deliver:
    description: >
      Job for generating a release, along with corresponding git tags, for a
      Lerna-based mono-repository.
      https://circleci.com/orbs/registry/orb/hutson/library-release-workflows
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - run: sudo apt install rsync
      - add_ssh_keys:
          fingerprints:
            - "58:7a:36:83:61:28:2c:c9:83:b1:c5:57:26:a9:fc:11"
      - run: >-
          git config --global user.email "circleci@circleci" && git config --global user.name "CircleCI"
      - run: yarn install
      - run: yarn build
      - run: yarn test & yarn lint --quiet
      - run: yarn version:release --yes

  deploy:
    description: >
      Job for publishing multiple npm packages from a Lerna-based mono-repository to
      an npm-compatible package registry.
      https://circleci.com/orbs/registry/orb/hutson/library-release-workflows
    docker:
      - image: >-
          circleci/node:12.16.2
    steps:
      - checkout
      - run: sudo apt install rsync
      - run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - run: yarn install
      - run: yarn build
      # After major version is releases, change this to use "beta" tag and "mainline" to use "latest"
      # Seems from-git does not work as version is already run and committed in "deliver" job
      # `from-git No tagged release found`
      # Adding `--dist-tag latest` to override the publishConfig of beta in projects until releases
      # otherwise is cumbersome to get latest version as stuck of earlier release
      - run: yarn lerna publish from-package --dist --dist-tag latest --pre-dist-tag latest --yes

workflows:
  version: 2
  # Should only be run on release branches
  deliver_deploy:
    jobs:
      - deliver:
          filters:
            branches:
              only: prerelease/beta
      - deploy:
          requires:
            - deliver
          filters:
            branches:
              only: prerelease/beta
  # Should be run on all activity to verify commits for pull-requests
  verify:
    jobs:
      - git_hygiene
      - build_and_test
